
name: Deploy Site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Yarn upgrade
        run: yarn upgrade

      - name: Action git config
        run: |
          git config --local user.email "$(git log --format='%ae' -n 1)"
          git config --local user.name "$(git log --format='%ae' -n 1)"
          git config --local committer.email "Patrick+githubaction@patrickauld.com"
          git config --local committer.name "Mandias GH Page Deploy Bot Action"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/PatrickAuld/mandias.github.io.git

      # Runs a single command using the runners shell
      - name: Build and deploy to gh-pages
        run: yarn deploy